.\"	 Manpage for easter.
.\" 	This file is part of Easter.
.\"
.\"     Easter is free software: you can redistribute it and/or modify
.\"     it under the terms of the GNU General Public License as published by
.\"     the Free Software Foundation, either version 3 of the License, or
.\"     (at your option) any later version.
.\" 
.\"     Easter is distributed in the hope that it will be useful,
.\"     but WITHOUT ANY WARRANTY; without even the implied warranty of
.\"     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
.\"     GNU General Public License for more details.
.\" 
.\"     You should have received a copy of the GNU General Public License
.\"     along with this program.  If not, see <http://www.gnu.org/licenses/>.
.\"     
.\"     The author can be contacted at <jtrubat@uoc.edu>
.TH EASTER 1 "3 November 2016" "1.1" "easter man page"
.SH NAME
\fBeaster\fR - Displays the date of Easter.
.SH SYNOPSIS
\fBeaster\fR [ -13ywojhHv ] [-A \fInumber\fR] [-B \fInumber\fR] [ \fIyear ...\fR ]
.SH DESCRIPTION
\fBeaster\fR displays the date of easter for a given year - list of years. If
arguments are not specified, the date for the current year is displayed.
.SH OPTIONS
.IP \fB-y\fR
Display the date of Easter for the specified year. Without argument the current
year is implied.
.TP
.B "-w, --western"
Western Easter after gregorian calendar. For year 1583 on this is the
default.
.TP
.B "-o, --orthodox"
Orthodox Easter after gregorian calendar.
.TP
.B "-j, --julian"
Julian Easter. For year before 1583 this is the default.
.TP
.B "-H, --header"
Display headers for Western, Eastern or Julian Easter.
.IP \fB-3\fR
Display the previous, current and next date of Easter surrounding the specified
year.
.IP \fB-1\fR
Display only date of Easter for the current year. This is the default.
.TP
.BI \-A " number"
Years to add after. The specified number of years is added to the end of the
display. This is in addition to any date range selected by the -y, -3, or -1
options. Negative numbers are allowed, in which case the specified number of
years is subtracted. For example,  "easter -y -B-2" produces the same
results as "easter -y -A2": shows Easter date for the current year and the next
two following years.
.TP
.BI \-B " number"
Years to add before. The specified number of years is added to the beginning of
the display. See
.BI \-A 
for examples.
.TP
.B "-h, --help"
Print this usage and exit.
.TP
.B "-v, --version"
Print version information and exit. 
.SH EXAMPLES
Assuming current year is 2016:
.LP
$ easter
.br
March 27 2016
.LP
$ easter -y 2000
.br
April 23 2000
.LP
$ easter 2005 2010 2015
.br
April 23 2000
.br
April  4 2010
.br
April  5 2015
.LP
$ easter -3
.br
April  5 2015
.br
March 27 2016
.br
April 16 2017
.LP
$ easter 2000 -A5
.br
April 23 2000
.br
April 15 2001
.br
March 31 2002
.br
April 20 2003
.br
April 11 2004
.br
March 27 2005
.LP
$ easter 900
.br
April 20 900
.LP
$ easter -j 2000
.br
April 17 2000
.LP
$ easter -o 2000
.br
April 30 2000
.LP
$ easter -woH -A3 2000
.br
Western		Orthodox
.br
April 23 2000	April 30 2000	
.br
April 15 2001	April 15 2001	
.br
March 31 2002	May    5 2002	
.br
April 20 2003	April 27 2003	
.SH AUTHOR
Jordi Trubat.
.SH REPORTING BUGS
Report bugs to <jtrubat@uoc.edu>
.SH COPYRIGHT
Copyright (C) 2016 Free Software Foundation, Inc. <http://fsf.org/>
.br
This is free software with ABSOLUTELY NO WARRANTY.
.SH SEE ALSO
.BR ncal (1)

